# -*- coding: utf-8 -*-
"""retail data_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtRaolv4S5Hq9_wiwemnhbChE--J0m75
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/retail_sales_dataset[1].csv")

df.head()

df['Date'] = pd.to_datetime(df['Date'])

particular_day=df[(df["Date"]=="2023-1-1")]
result=particular_day.groupby('Product Category')["Total Amount"].sum().reset_index()
display(result)

xpoint=result["Product Category"]
ypoint=result["Total Amount"]
plt.bar(xpoint,ypoint)
plt.show()